FROM node:12.16.1-alpine as builder

WORKDIR /opt/historical-data-store

RUN apk add --no-cache -t build-dependencies git make gcc g++ python libtool autoconf automake \
    && cd $(npm root -g)/npm \
    && npm config set unsafe-perm true \
    && npm install -g node-gyp

COPY package.json package-lock.json* /opt/historical-data-store/

RUN npm ci

RUN apk del build-dependencies

COPY tsconfig.json /opt/historical-data-store/
COPY src /opt/historical-data-store/src

RUN npm run build

CMD ["node", "build/index.js"]