FROM --platform=${TARGETPLATFORM:-linux/amd64} ghcr.io/openfaas/of-watchdog:0.8.4 as watchdog
FROM --platform=${TARGETPLATFORM:-linux/amd64} node:14-alpine as ship

ARG TARGETPLATFORM
ARG BUILDPLATFORM

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

RUN addgroup -S app && adduser -S -g app app

RUN apk --no-cache add curl ca-certificates

RUN apk add --no-cache -t build-dependencies git make gcc g++ python libtool autoconf automake yarn \
    && cd $(npm root -g)/npm \
    && npm config set unsafe-perm true \
    && npm install -g node-gyp

# Turn down the verbosity to default level.
ENV NPM_CONFIG_LOGLEVEL warn

# chmod for tmp is for a buildkit issue
RUN chown app:app -R /home/app \
    && chmod 777 /tmp

# Create a folder named function
RUN mkdir -p /home/app

# Wrapper/boot-strapper
WORKDIR /home/app

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

# Install dependencies
# RUN yarn run cleanup

# Install dependencies
RUN yarn install

COPY ./src ./src

# Build the project
RUN yarn run build

# Environment variables for openfaas
ENV cgi_headers="true"
ENV fprocess="node ./build/index.js"
ENV mode="http"
ENV upstream_url="http://127.0.0.1:3000"

ENV exec_timeout="10s"
ENV write_timeout="15s"
ENV read_timeout="15s"

ENV REDIS_AUTH='TjEmUWes67'
ENV REDIS_HOST='my-redis-master'
# ENV REDIS_AUTH='4ikHQfBqMA'
# ENV REDIS_HOST='10.75.132.57'
ENV REDIS_PORT=6379
ENV REDIS_DB=0
ENV TYPOLOGY_MAP='[{"typologyName":"typology28","typologyEndpoint":"http://gateway:8080/function/off-typology-28/execute","rules":[{"ruleName":"rule2","ruleEndpoint":"http://gateway:8080/function/off-rule-002/execute"}]},{"typologyName":"typology214","typologyEndpoint":"http://gateway:8080/function/off-typology-214/execute","rules":[{"ruleName":"rule3","ruleEndpoint":"http://gateway:8080/function/off-rule-003/execute"}]}]'
ENV HOST_PORT=3000

ENV prefix_logs="false"

HEALTHCHECK --interval=60s CMD [ -e /tmp/.lock ] || exit 1

# Execute watchdog command
CMD ["fwatchdog"]