FROM --platform=${TARGETPLATFORM:-linux/amd64} node:14.15.0-alpine as ship

ARG TARGETPLATFORM

WORKDIR /opt/tms-service

RUN apk --no-cache add curl ca-certificates \
    && addgroup -S app && adduser -S -g app app

RUN apk add --no-cache -t build-dependencies git make gcc g++ python libtool autoconf automake yarn

COPY package.json yarn.lock /opt/tms-service/

RUN yarn install

RUN apk del build-dependencies

COPY tsconfig.json /opt/tms-service/

COPY src /opt/tms-service/src

RUN yarn run build

CMD ["yarn", "start"]
