swagger: '2.0'
info:
  title: 'Swagger Example'
  description: >
    FRM transaction validation.
  version: '0.1.0'
schemes:
  - 'http'
paths:
  /:
    get:
      summary: 'Check the status of the service'
      description: "If the service is up and running correctly the response will be 'UP'"
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/Health'
        500:
          $ref: '#/responses/500'
  /health:
    get:
      summary: 'Check the status of the service'
      description: "If the service is up and running correctly the response will be 'UP'"
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/Health'
        500:
          $ref: '#/responses/500'
  /execute:
    post:
      summary: 'Monitor transaction'
      description: 'Mojaloop Transation'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Validates request params'
          required: true
          schema:
            $ref: '#/definitions/mojaloopQuotePostRequest'
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/CustomerCreditTransferInitiationV11'
        400:
          $ref: '#/responses/400'
        401:
          $ref: '#/responses/401'
        500:
          $ref: '#/responses/500'
  /transfers:
    post:
      summary: 'Transfer'
      description: 'Mojaloop transfer message interpreter'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Validates request params'
          required: true
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/Transfer'
        400:
          $ref: '#/responses/400'
        401:
          $ref: '#/responses/401'
        500:
          $ref: '#/responses/500'

responses:
  400:
    description: Bad Request
    schema:
      $ref: '#/definitions/Error'
  401:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Health:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
          - 'UP'
          - 'DOWN'
  Transfer:
    type: 'object'
  Transaction:
    type: 'object'
    required:
      - AuthenticationType
    properties:
      AuthenticationType:
        type: string
  TransactionType:
    type: 'object'
    required:
      - TransactionScenario
    properties:
      TransactionScenario:
        type: string
      TransactionInitiator:
        type: string
      TransactionInitiatorType:
        type: string
  partyIdInfo:
    type: 'object'
    required:
      - partyIdType
      - partyIdentifier
      - fspId
  complexName:
    required:
      - firstName
      - lastName
  personalInfo:
    type: 'object'
    required:
      - complexName
      - dateOfBirth
    properties:
      complexName:
        $ref: '#/definitions/complexName'
      dateOfBirth:
        type: 'string'
  Payer:
    type: 'object'
    required:
      - partyIdInfo
      - personalInfo
    properties:
      partyIdInfo:
        $ref: '#/definitions/partyIdInfo'
      personalInfo:
        $ref: '#/definitions/personalInfo'
  Payee:
    type: 'object'
    required:
      - partyIdInfo
    properties:
      partyIdInfo:
        $ref: '#/definitions/partyIdInfo'
  amount:
    type: 'object'
    required:
      - amount
      - currency
  transactionType:
    type: 'object'
    required:
      - scenario
      - initiator
      - initiatorType
  mojaloopQuotePostRequest:
    type: 'object'
    required:
      - quoteId
      - transactionId
      - payer
      - payee
      - amountType
      - amount
      - transactionType
    properties:
      quoteId:
        type: string
      transactionId:
        type: string
      payer:
        $ref: '#/definitions/Payer'
      payee:
        $ref: '#/definitions/Payee'
      amountType:
        type: string
      amount:
        $ref: '#/definitions/amount'
      transactionType:
        $ref: '#/definitions/transactionType'
  CustomerCreditTransferInitiationV11:
    type: object
    properties:
      GroupHeader:
        $ref: '#/definitions/GroupHeader'
      PaymentInformation:
        $ref: '#/definitions/PaymentInformation'
      SupplementaryData:
        $ref: '#/definitions/SupplementaryData'
    required:
      - GroupHeader
      - PaymentInformation
  PaymentInformation:
    type: object
    properties:
      PaymentInformationIdentification:
        type: string
        maxLength: 35
      CreditTransferTransactionInformation:
        type: object
        properties:
          PaymentIdentification:
            type: object
            properties:
              EndToEndIdentification:
                type: string
                maxLength: 35
            required:
              - EndToEndIdentification
          CreditorAccount:
            type: object
            properties:
              Identification:
                type: object
                properties:
                  Identification:
                    type: string
                  Other:
                    type: object
                    properties:
                      Identification:
                        type: string
                        maxLength: 34
                      SchemeName:
                        type: object
                        properties:
                          Proprietary:
                            type: string
                            maxLength: 35
                        required:
                          - Proprietary
                      PrivateIdentification:
                        type: object
                        properties:
                          DateAndPlaceOfBirth:
                            type: object
                            properties:
                              Birthdate:
                                type: string
                      ContactDetails:
                        type: object
                        properties:
                          MobileNumber:
                            type: string
                    required:
                      - Identification
                  SchemeName:
                    type: object
                    properties:
                      Proprietary:
                        type: string
                        maxLength: 35
                    required:
                      - Proprietary
                  PrivateIdentification:
                    type: object
                    properties:
                      DateAndPlaceOfBirth:
                        type: object
                        properties:
                          Birthdate:
                            type: string
                  ContactDetails:
                    type: object
                    properties:
                      MobileNumber:
                        type: string
              Proxy:
                type: string
              Name:
                type: string
          CreditorAgent:
            type: object
            properties:
              FinancialInstitutionIdentification:
                type: object
                properties:
                  ClearingSystemMemberIdentification:
                    type: object
                    properties:
                      MemberIdentification:
                        type: string
                        maxLength: 35
                    required:
                      - MemberIdentification
          Creditor:
            type: object
            properties:
              Name:
                type: string
                maxLength: 140
              Identification:
                type: object
                properties:
                  Identification:
                    type: string
                  Other:
                    type: object
                    properties:
                      Identification:
                        type: string
                      SchemeName:
                        type: object
                        properties:
                          Proprietary:
                            type: string
                            maxLength: 35
                        required:
                          - Proprietary
                      PrivateIdentification:
                        type: object
                        properties:
                          DateAndPlaceOfBirth:
                            type: object
                            properties:
                              Birthdate:
                                type: string
                                format: date
                              ProvinceOfBirth:
                                type: string
                              CityOfBirth:
                                type: string
                                maxLength: 35
                              CountryOfBirth:
                                type: string
                                pattern: '[A-Z]{2,2}'
                            required:
                              - Birthdate
                              - CityOfBirth
                              - CountryOfBirth
                      ContactDetails:
                        type: object
                        properties:
                          MobileNumber:
                            type: string
                  SchemeName:
                    type: object
                    properties:
                      Proprietary:
                        type: string
                        maxLength: 35
                    required:
                      - Proprietary
                  PrivateIdentification:
                    type: object
                    properties:
                      DateAndPlaceOfBirth:
                        type: object
                        properties:
                          Birthdate:
                            type: string
                  ContactDetails:
                    type: object
                    properties:
                      MobileNumber:
                        type: string
          Amount:
            type: object
            properties:
              InstructedAmount:
                type: object
              EquivalentAmount:
                type: object
                properties:
                  CurrencyOfTransfer:
                    type: string
                    pattern: '[A-Z]{3,3}'
                  Amount:
                    type: number
                    format: float
                    minimum: 0
                    exclusiveMinimum: true
                required:
                  - CurrencyOfTransfer
                  - Amount
          SupplementaryData:
            type: object
            properties:
              fees.currency:
                type: string
              fees.amount:
                type: number
                format: float
                minimum: 0
          PaymentTypeInformation:
            type: object
            properties:
              CategoryPurpose:
                type: object
                properties:
                  Proprietary:
                    type: string
                    maxLength: 35
                required:
                  - Proprietary
          RegulatoryReporting:
            type: object
            properties:
              Details:
                type: object
                properties:
                  Code:
                    type: string
                    maxLength: 10
          RemittanceInformation:
            type: object
            properties:
              Structured:
                type: object
                properties:
                  AdditionalRemittanceInformation:
                    type: string
                    maxLength: 140
      DebtorAccount:
        type: object
        properties:
          Identification:
            type: object
            properties:
              Identification:
                type: string
              Other:
                type: object
                properties:
                  Identification:
                    type: string
                    maxLength: 34
                  SchemeName:
                    type: object
                    properties:
                      Proprietary:
                        type: string
                        maxLength: 35
                    required:
                      - Proprietary
                  PrivateIdentification:
                    type: object
                    properties:
                      DateAndPlaceOfBirth:
                        type: object
                        properties:
                          Birthdate:
                            type: string
                  ContactDetails:
                    type: object
                    properties:
                      MobileNumber:
                        type: string
              SchemeName:
                type: object
                properties:
                  Proprietary:
                    type: string
                    maxLength: 35
                required:
                  - Proprietary
              PrivateIdentification:
                type: object
                properties:
                  DateAndPlaceOfBirth:
                    type: object
                    properties:
                      Birthdate:
                        type: string
              ContactDetails:
                type: object
                properties:
                  MobileNumber:
                    type: string
            required:
              - Identification
          Proxy:
            type: string
          Name:
            type: string
            maxLength: 140
      DebtorAgent:
        type: object
        properties:
          FinancialInstitutionIdentification:
            type: object
            properties:
              ClearingSystemMemberIdentification:
                type: object
                properties:
                  MemberIdentification:
                    type: string
                    maxLength: 35
                required:
                  - MemberIdentification
      Debtor:
        type: object
        properties:
          Name:
            type: string
            maxLength: 140
          Identification:
            type: object
            properties:
              Identification:
                type: string
              Other:
                type: object
                properties:
                  Identification:
                    type: string
                  SchemeName:
                    type: object
                    properties:
                      Proprietary:
                        type: string
                        maxLength: 35
                    required:
                      - Proprietary
                  PrivateIdentification:
                    type: object
                    properties:
                      DateAndPlaceOfBirth:
                        type: object
                        properties:
                          Birthdate:
                            type: string
                  ContactDetails:
                    type: object
                    properties:
                      MobileNumber:
                        type: string
              SchemeName:
                type: object
                properties:
                  Proprietary:
                    type: string
                    maxLength: 35
                required:
                  - Proprietary
              PrivateIdentification:
                type: object
                properties:
                  DateAndPlaceOfBirth:
                    type: object
                    properties:
                      Birthdate:
                        type: string
                        format: date
                      ProvinceOfBirth:
                        type: string
                      CityOfBirth:
                        type: string
                        maxLength: 35
                      CountryOfBirth:
                        type: string
                        pattern: '[A-Z]{2,2}'
                    required:
                      - Birthdate
                      - CityOfBirth
                      - CountryOfBirth
              ContactDetails:
                type: object
                properties:
                  MobileNumber:
                    type: string
    required:
      - PaymentInformationIdentification
      - CreditTransferTransactionInformation
      - DebtorAccount
      - DebtorAgent
      - Debtor
  SupplementaryData:
    type: object
    properties:
      payee.merchantClassificationCode:
        type: string
      payer.merchantClassificationCode:
        type: string
      transactionType.initiatorType:
        type: string
      geoCode.latitude:
        type: string
      geoCode.longitude:
        type: string
  GroupHeader:
    type: object
    properties:
      InitiatingParty:
        type: object
        properties:
          Name:
            type: string
            maxLength: 140
          Identification:
            type: object
            properties:
              Identification:
                type: string
              Other:
                type: object
                properties:
                  Identification:
                    type: string
                  SchemeName:
                    type: object
                    properties:
                      Proprietary:
                        type: string
                        maxLength: 35
                    required:
                      - Proprietary
                  PrivateIdentification:
                    type: object
                    properties:
                      DateAndPlaceOfBirth:
                        type: object
                        properties:
                          Birthdate:
                            type: string
                  ContactDetails:
                    type: object
                    properties:
                      MobileNumber:
                        type: string
              SchemeName:
                type: object
                properties:
                  Proprietary:
                    type: string
                    maxLength: 35
                required:
                  - Proprietary
              PrivateIdentification:
                type: object
                properties:
                  DateAndPlaceOfBirth:
                    type: object
                    properties:
                      Birthdate:
                        type: string
              ContactDetails:
                type: object
                properties:
                  MobileNumber:
                    type: string
                    pattern: '\+[0-9]{1,3}-[0-9()+\-]{1,30}'

  Error:
    type: 'object'
    properties:
      data:
        type: 'object'
        properties:
          error:
            type: 'string'
parameters:
  accept:
    in: header
    name: accept
    type: string
    required: true
  content-length:
    in: header
    name: content-length
    type: string
    required: true
  content-type:
    in: header
    name: content-type
    type: string
    required: true
